trigger:
- main

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Debug:
        Configuration: 'Debug'
        IsDebug: true
      Release:
        Configuration: 'Release'
        IsDebug: false
    maxParallel: 1
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 7.0.202'
    inputs:
      packageType: 'sdk'
      version: '7.0.202'

  - task: DotNetCoreCLI@2
    displayName: Build MakeLink
    inputs:
      command: 'build'
      arguments: '--configuration $(Configuration)'

  - task: DotNetCoreCLI@2
    displayName: Test MakeLink
    inputs:
      command: 'test'
      projects: 'tests/MakeLink.UnitTests/MakeLink.UnitTests.csproj'
      arguments: '--configuration $(Configuration) --no-build --collect "Code coverage"'

  - task: DotNetCoreCLI@2
    displayName: Pack Nuget
    inputs:
      command: 'pack'
      packagesToPack: 'src/MakeLink/MakeLink.csproj'
      configuration: '$(Configuration)'
      nobuild: true
      includesymbols: $(IsDebug)
      versioningScheme: 'off'

  - task: PublishBuildArtifacts@1
    displayName: Publish Nuget
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Nuget-$(Configuration)'
      publishLocation: 'Container'
